# 系统环境
profile: dev

blocksgoroutinesize: 6
blockschannelsize: 64
txschannelsize: 64
chainheadeventchannelsize: 10
newtxseventchannelsize: 10
timeout: '10s'
reexec: 128
# dummy, http, mongo
saver: 'dummy'
#saver: 'http'
subscribeendpointlist: ['']
batchsize: 12